"""Tests for the OWASP CRS pattern set (Layer 3 data) and its extractor.

Two groups, mirroring ``test_sigma_pairs.py``:

* **Data integrity** — validates the shipped ``crs_patterns.json``. These guard
  against a bad regeneration being committed, and the most important of them is
  that every pattern still compiles: a rule set that cannot be loaded takes the
  whole module down at import, not at match time.
* **Extraction logic** — unit-tests ``core/scripts/extract_crs_patterns.py``.
  It has no third-party dependency, so these always run.

Per ``docs/waf_payload_analyzer.md`` D3 the extraction is deliberately partial,
so several tests assert on *provenance* rather than coverage: what matters is
not that every rule survived, but that everything which did not is counted.
"""
from __future__ import annotations

import json
import re
import unittest
from pathlib import Path

from core.scripts import extract_crs_patterns as ex

DATA_FILE = Path(__file__).resolve().parents[1] / "core" / "data" / "crs_patterns.json"


def _load() -> dict:
    return json.loads(DATA_FILE.read_text(encoding="utf-8"))


class TestDataIntegrity(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.doc = _load()
        cls.rules = cls.doc["rules"]

    def test_file_is_not_empty(self) -> None:
        self.assertGreater(len(self.rules), 100)

    def test_every_regex_rule_compiles(self) -> None:
        # The extractor compile-verifies before emitting, so a failure here means
        # the shipped file was edited by hand or generated by an older version.
        for rule in self.rules:
            if rule["match"] != "regex":
                continue
            with self.subTest(rule_id=rule["rule_id"]):
                try:
                    re.compile(rule["pattern"])
                except re.error as exc:
                    self.fail(f"rule {rule['rule_id']} does not compile: {exc}")

    def test_every_rule_has_the_documented_keys(self) -> None:
        required = {
            "rule_id", "category", "match", "severity", "severity_weight",
            "paranoia_level", "targets", "transformations", "message",
            "crs_file", "dropped_conditions",
        }
        for rule in self.rules:
            with self.subTest(rule_id=rule["rule_id"]):
                self.assertTrue(required.issubset(rule.keys()))

    def test_match_kind_and_payload_agree(self) -> None:
        for rule in self.rules:
            with self.subTest(rule_id=rule["rule_id"]):
                if rule["match"] == "regex":
                    self.assertIn("pattern", rule)
                else:
                    self.assertEqual(rule["match"], "phrases")
                    self.assertTrue("phrases" in rule or "phrase_list" in rule)

    def test_phrase_list_references_all_resolve(self) -> None:
        # A rule pointing at a missing word list would match nothing while
        # claiming to be active — the quietest possible failure.
        lists = self.doc["phrase_lists"]
        for rule in self.rules:
            name = rule.get("phrase_list")
            if name:
                with self.subTest(rule_id=rule["rule_id"]):
                    self.assertIn(name, lists)
                    self.assertTrue(lists[name])

    def test_no_orphan_phrase_lists(self) -> None:
        referenced = {r["phrase_list"] for r in self.rules if r.get("phrase_list")}
        self.assertEqual(set(self.doc["phrase_lists"]), referenced)

    def test_severity_weight_matches_severity(self) -> None:
        for rule in self.rules:
            with self.subTest(rule_id=rule["rule_id"]):
                self.assertEqual(
                    rule["severity_weight"],
                    ex.SEVERITY_WEIGHTS.get(rule["severity"], 1.0),
                )

    def test_rule_ids_are_unique(self) -> None:
        ids = [r["rule_id"] for r in self.rules]
        self.assertEqual(len(ids), len(set(ids)))

    def test_libinjection_rules_are_absent_and_counted(self) -> None:
        # D1: @detectSQLi / @detectXSS cannot be extracted. Their absence must be
        # a counted drop, not a silent one.
        counters = self.doc["_meta"]["counters"]
        self.assertGreater(counters["dropped_unextractable_operator"], 0)
        for rule in self.rules:
            self.assertNotIn("detectSQLi", rule.get("pattern", ""))
            self.assertNotIn("detectXSS", rule.get("pattern", ""))

    def test_sqli_and_xss_are_covered_by_regex_rules(self) -> None:
        # The load-bearing claim behind D1: dropping libinjection is affordable
        # because CRS carries its own SQLi and XSS patterns. If these counts ever
        # collapse, D1 needs revisiting.
        by_category: dict[str, int] = {}
        for rule in self.rules:
            by_category[rule["category"]] = by_category.get(rule["category"], 0) + 1
        self.assertGreaterEqual(by_category.get("sqli", 0), 30)
        self.assertGreaterEqual(by_category.get("xss", 0), 15)

    def test_paranoia_levels_are_carried(self) -> None:
        # CRS's own model treats higher levels as progressively noisier. A
        # consumer that cannot see the level inherits that noise blind.
        levels = {r["paranoia_level"] for r in self.rules}
        self.assertTrue(levels.issubset({1, 2, 3, 4}))
        self.assertIn(1, levels)

    def test_partial_extractions_are_flagged_individually(self) -> None:
        partial = [r for r in self.rules if r["dropped_conditions"]]
        self.assertEqual(len(partial), self.doc["_meta"]["partial_extraction_count"])
        self.assertTrue(partial, "expected some rules to be partially extracted")

    def test_no_rule_claims_completeness_it_lacks(self) -> None:
        # Every dropped_conditions note must name a cause, not be a bare marker.
        for rule in self.rules:
            for note in rule["dropped_conditions"]:
                with self.subTest(rule_id=rule["rule_id"]):
                    self.assertGreater(len(note), 20)

    def test_meta_records_provenance(self) -> None:
        meta = self.doc["_meta"]
        self.assertIn("coreruleset", meta["project"])
        self.assertIn("Apache", meta["license"])
        self.assertEqual(meta["rule_count"], len(self.rules))


class TestPcreTranslation(unittest.TestCase):
    def test_hex_brace_becomes_a_byte_escape(self) -> None:
        self.assertEqual(ex.pcre_to_python(r"\x{bc}"), r"\xbc")

    def test_wide_codepoints_widen_the_escape(self) -> None:
        # Expectations are built from chr(92) rather than written as literals.
        # A source line carrying a real U+2028 is a line separator to some
        # tooling, and this file was mangled that way once already.
        backslash = chr(92)
        self.assertEqual(ex.pcre_to_python(r"\x{2028}"), backslash + "u2028")
        self.assertEqual(ex.pcre_to_python(r"\x{1f600}"), backslash + "U0001f600")

    def test_wide_codepoint_escape_still_matches_its_character(self) -> None:
        translated = ex.pcre_to_python(r"\x{2028}")
        self.assertTrue(re.compile(translated).search(chr(0x2028)))

    def test_absolute_end_anchor_is_translated(self) -> None:
        self.assertEqual(ex.pcre_to_python(r"foo\z"), r"foo\Z")

    def test_translation_preserves_meaning_not_just_compilability(self) -> None:
        # The regression this whole function exists for. The obvious fix for an
        # uncompilable \x{bc} is to pad the bare \x to \x00, which compiles and
        # silently rewrites the pattern into something that no longer matches the
        # payload the rule was written for.
        source = r"\x{bc}[^>\x{be}]*[>\x{be}]"
        translated = ex.pcre_to_python(source)
        probe = "¼ script ¾"
        self.assertTrue(re.compile(translated).search(probe))

        naive = re.sub(r"\\x(?![0-9A-Fa-f]{2})", r"\\x00", source)
        self.assertFalse(
            re.compile(naive).search(probe),
            "the naive fix started matching — this test no longer guards anything",
        )

    def test_untouched_pattern_is_returned_unchanged(self) -> None:
        plain = r"(?i)union\s+select"
        self.assertEqual(ex.pcre_to_python(plain), plain)

    def test_escaped_backslash_z_is_not_an_anchor(self) -> None:
        # \\z is a literal backslash followed by z, not PCRE's end anchor.
        self.assertEqual(ex.pcre_to_python(r"a\\z"), r"a\\z")


class TestQuotedBlocks(unittest.TestCase):
    def test_splits_operand_from_actions(self) -> None:
        stmt = 'SecRule ARGS "@rx foo" "id:1,severity:\'CRITICAL\'"'
        self.assertEqual(ex.quoted_blocks(stmt), ["@rx foo", "id:1,severity:'CRITICAL'"])

    def test_escaped_quote_inside_a_pattern_does_not_split(self) -> None:
        # CRS operands are regexes full of quotes and escapes — the exact input
        # that makes a quote-matching regex quietly wrong.
        stmt = r'SecRule ARGS "@rx [\"\x27]+union" "id:2"'
        blocks = ex.quoted_blocks(stmt)
        self.assertEqual(len(blocks), 2)
        self.assertIn("union", blocks[0])
        self.assertEqual(blocks[1], "id:2")

    def test_bracketed_regex_survives_intact(self) -> None:
        stmt = 'SecRule ARGS "@rx (?:[/\\x5c]|%2f){2,3}" "id:3"'
        self.assertEqual(ex.quoted_blocks(stmt)[0], "@rx (?:[/\\x5c]|%2f){2,3}")


class TestExtractionLogic(unittest.TestCase):
    @staticmethod
    def _stats() -> dict[str, int]:
        return {
            "statements_seen": 0, "extracted_regex": 0, "extracted_phrases": 0,
            "pcre_translated": 0, "dropped_uncompilable": 0,
            "dropped_unextractable_operator": 0, "dropped_pm_inline": 0,
            "skipped_control_flow": 0, "skipped_other_operator": 0,
            "skipped_malformed": 0, "skipped_no_id": 0,
        }

    def test_control_flow_rules_are_skipped_not_dropped(self) -> None:
        # A paranoia-level gate has no severity and was never a detection. It
        # must not count against the extraction yield.
        conf = (
            'SecRule TX:DETECTION_PARANOIA_LEVEL "@lt 1" '
            '"id:930011,phase:1,pass,nolog,skipAfter:END-REQUEST-930"\n'
        )
        stats = self._stats()
        records = ex.extract_from_file("f.conf", conf, "lfi", stats)
        self.assertEqual(records, [])
        self.assertEqual(stats["skipped_control_flow"], 1)
        self.assertEqual(stats["dropped_uncompilable"], 0)

    def test_libinjection_rule_is_dropped_and_counted(self) -> None:
        conf = (
            'SecRule ARGS "@detectSQLi" '
            '"id:942100,phase:2,block,severity:\'CRITICAL\',msg:\'SQLi\'"\n'
        )
        stats = self._stats()
        records = ex.extract_from_file("f.conf", conf, "sqli", stats)
        self.assertEqual(records, [])
        self.assertEqual(stats["dropped_unextractable_operator"], 1)

    def test_continuation_lines_are_joined(self) -> None:
        conf = (
            'SecRule ARGS "@rx union\\s+select" \\\n'
            '    "id:942190,\\\n'
            '    severity:\'CRITICAL\',\\\n'
            '    t:none,t:urlDecodeUni,\\\n'
            '    tag:\'paranoia-level/2\'"\n'
        )
        stats = self._stats()
        records = ex.extract_from_file("f.conf", conf, "sqli", stats)
        self.assertEqual(len(records), 1)
        record = records[0]
        self.assertEqual(record["rule_id"], "942190")
        self.assertEqual(record["paranoia_level"], 2)
        self.assertEqual(record["transformations"], ["none", "urlDecodeUni"])
        self.assertEqual(record["severity_weight"], 5.0)

    def test_unsupported_transformation_is_recorded_not_hidden(self) -> None:
        conf = (
            'SecRule ARGS "@rx alert" '
            '"id:941110,severity:\'CRITICAL\',t:none,t:jsDecode"\n'
        )
        records = ex.extract_from_file("f.conf", conf, "xss", self._stats())
        self.assertEqual(len(records), 1)
        notes = " ".join(records[0]["dropped_conditions"])
        self.assertIn("jsDecode", notes)

    def test_header_only_rule_is_flagged_as_target_mismatch(self) -> None:
        conf = (
            'SecRule REQUEST_HEADERS:User-Agent "@rx curl" '
            '"id:913100,severity:\'CRITICAL\',t:none"\n'
        )
        records = ex.extract_from_file("f.conf", conf, "protocol", self._stats())
        notes = " ".join(records[0]["dropped_conditions"])
        self.assertIn("target mismatch", notes)

    def test_args_rule_is_not_flagged(self) -> None:
        conf = 'SecRule ARGS "@rx union" "id:1,severity:\'CRITICAL\',t:none"\n'
        records = ex.extract_from_file("f.conf", conf, "sqli", self._stats())
        self.assertEqual(records[0]["dropped_conditions"], [])

    def test_negated_operator_is_recorded(self) -> None:
        conf = 'SecRule ARGS "!@rx ^\\d+$" "id:2,severity:\'CRITICAL\',t:none"\n'
        records = ex.extract_from_file("f.conf", conf, "protocol", self._stats())
        notes = " ".join(records[0]["dropped_conditions"])
        self.assertIn("negated", notes)

    def test_uncompilable_pattern_is_dropped_not_weakened(self) -> None:
        conf = 'SecRule ARGS "@rx (unclosed" "id:3,severity:\'CRITICAL\',t:none"\n'
        stats = self._stats()
        records = ex.extract_from_file("f.conf", conf, "sqli", stats)
        self.assertEqual(records, [])
        self.assertEqual(stats["dropped_uncompilable"], 1)

    def test_pm_from_file_becomes_a_phrase_reference(self) -> None:
        conf = (
            'SecRule ARGS "@pmFromFile lfi-os-files.data" '
            '"id:930120,severity:\'CRITICAL\',t:none"\n'
        )
        stats = self._stats()
        records = ex.extract_from_file("f.conf", conf, "lfi", stats)
        self.assertEqual(records[0]["match"], "phrases")
        self.assertEqual(records[0]["phrase_list"], "lfi-os-files.data")
        self.assertEqual(stats["extracted_phrases"], 1)

    def test_phrase_list_parser_strips_comments_and_blanks(self) -> None:
        text = "# comment\n\n.htaccess\n  .htpasswd  \n\n# another\n"
        self.assertEqual(ex.parse_phrase_list(text), [".htaccess", ".htpasswd"])


if __name__ == "__main__":
    unittest.main()
